name: Build and deploy the website
on: [push]
jobs:
    build:
        name: Build Docusaurus project
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: yarn

            - name: Install Yarn dependencies
              run: yarn install --immutable

            - name: Docusaurus .docusaurus folder cache
              id: cache-docusaurus-cache
              uses: actions/cache@v4
              with:
                  path: .docusaurus
                  key: ${{ runner.os }}-docusaurus-cache

            - name: Docusaurus build folder cache
              id: cache-docusaurus-build
              uses: actions/cache@v4
              with:
                  path: build
                  key: ${{ runner.os }}-docusaurus-build

            - name: Build Docusaurus page
              run: yarn build
              env:
                  UMAMI_HOST: https://umami.wayspace.net
                  UMAMI_ID: a30ae129-e24f-490e-b4ea-3cd30e4fa743

            - name: Save build output
              uses: actions/upload-artifact@v4
              with:
                  name: docusau-build-out
                  path: build
    deploy:
        name: Deploy static website to S3
        if: github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Restore build output
              uses: actions/download-artifact@v5
              with:
                  name: docusau-build-out
                  path: build

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Upload to AWS S3
              run: aws s3 sync build s3://plugin-docs.surva.net --delete
